project:
  type: book

resources:
  - img/

book:
  title: "Regularização em MLGs"
  author: "Carlos de Moura"
  date: "12/1/2025"
  chapters:
    - index.qmd
    - qmd/regularização.qmd
    - qmd/estimação.qmd
    - qmd/tunagem.qmd
    - qmd/exemplo.qmd
    - qmd/referências.qmd

lang: pt

bibliography: qmd/references.bib
csl: apa-5th-edition.csl
nocite: |
  @*


format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: false
    css: styles.css
    include-after-body: script.js

    
execute:
  freeze: auto



