project:
  type: book

book:
  title: "2025_mlg_regularizacao"
  author: "Norah Jones"
  date: "11/20/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - regularização.qmd
    - estimação.qmd
    - tunagem.qmd
    - exemplos.qmd
    - referências.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    
execute:
  freeze: auto



